#include "ui_strings.h"

static const ui_strings_t LANG_RU = {
    .channel_1              = "КАНАЛ 1",
    .channel_2              = "КАНАЛ 2",
    .current_temp           = "ТЕКУЩАЯ",
    .setpoint               = "УСТАВКА",
    .settings               = "Настройки",
    .back                   = "< Назад",
    .sound                  = "Звук",
    .sleep                  = "Сон",
    .display                = "Дисплей",
    .units                  = "Единицы",
    .profiles               = "Профили",
    .about                  = "О системе",
    .lang_label             = "Язык / Language",
    .theme_label            = "Тема",
    .theme_dark             = "Тёмная",
    .theme_light            = "Светлая",
    .brightness             = "Яркость",
    .bl_timeout             = "Таймаут подсветки",
    .bl_1min                = "1 мин",
    .bl_5min                = "5 мин",
    .bl_never               = "Никогда",
    .units_c                = "°C",
    .units_f                = "°F",
    .sleep_timer_label      = "Таймер до сна",
    .sleep_temp_label       = "Температура сна",
    .sl_2min                = "2 мин",
    .sl_10min               = "10 мин",
    .save_current           = "Сохранить текущие",
    .factory_reset          = "Сброс к заводским",
    .confirm_factory_reset  = "Сброс к заводским настройкам?",
    .confirm_yes            = "Да",
    .confirm_no             = "Нет",
    .firmware               = "Прошивка",
    .uptime                 = "Наработка",
    .tool_type              = "Тип инструмента",
    .tool_iron              = "Паяльник",
    .tool_gun               = "Фен",
    .airflow                = "Поток",
    .pwr_label              = "МОЩ",
    .temp_step              = "Шаг температуры",
    .beep_touch             = "Бип при касании",
    .alert_overheat         = "Алерт перегрева",
    .alert_ready            = "Сигнал прогрева",
    .ch_color               = "Цвет канала",
    .add_profile            = "Добавить",
    .edit_profile           = "Изменить",
    .delete_profile         = "Удалить",
    .profile_name           = "Имя",
    .pid_kp                 = "Kp",
    .pid_ki                 = "Ki",
    .pid_kd                 = "Kd",
    .temp_offset            = "Смещение",
    .apply_ch1              = "Применить CH1",
    .apply_ch2              = "Применить CH2",
};

static const ui_strings_t LANG_EN = {
    .channel_1              = "CHANNEL 1",
    .channel_2              = "CHANNEL 2",
    .current_temp           = "CURRENT",
    .setpoint               = "SETPOINT",
    .settings               = "Settings",
    .back                   = "< Back",
    .sound                  = "Sound",
    .sleep                  = "Sleep",
    .display                = "Display",
    .units                  = "Units",
    .profiles               = "Profiles",
    .about                  = "About",
    .lang_label             = "Language",
    .theme_label            = "Theme",
    .theme_dark             = "Dark",
    .theme_light            = "Light",
    .brightness             = "Brightness",
    .bl_timeout             = "Backlight timeout",
    .bl_1min                = "1 min",
    .bl_5min                = "5 min",
    .bl_never               = "Never",
    .units_c                = "°C",
    .units_f                = "°F",
    .sleep_timer_label      = "Sleep timer",
    .sleep_temp_label       = "Sleep temperature",
    .sl_2min                = "2 min",
    .sl_10min               = "10 min",
    .save_current           = "Save current",
    .factory_reset          = "Factory reset",
    .confirm_factory_reset  = "Reset to factory settings?",
    .confirm_yes            = "Yes",
    .confirm_no             = "No",
    .firmware               = "Firmware",
    .uptime                 = "Uptime",
    .tool_type              = "Tool Type",
    .tool_iron              = "Iron",
    .tool_gun               = "Hot Air",
    .airflow                = "Airflow",
    .pwr_label              = "PWR",
    .temp_step              = "Temp step",
    .beep_touch             = "Touch beep",
    .alert_overheat         = "Overheat alert",
    .alert_ready            = "Ready alert",
    .ch_color               = "Channel color",
    .add_profile            = "Add",
    .edit_profile           = "Edit",
    .delete_profile         = "Delete",
    .profile_name           = "Name",
    .pid_kp                 = "Kp",
    .pid_ki                 = "Ki",
    .pid_kd                 = "Kd",
    .temp_offset            = "Offset",
    .apply_ch1              = "Apply CH1",
    .apply_ch2              = "Apply CH2",
};

static const ui_strings_t LANG_DE = {
    .channel_1              = "KANAL 1",
    .channel_2              = "KANAL 2",
    .current_temp           = "AKTUELL",
    .setpoint               = "SOLLWERT",
    .settings               = "Einstellungen",
    .back                   = "< Zurück",
    .sound                  = "Ton",
    .sleep                  = "Schlaf",
    .display                = "Anzeige",
    .units                  = "Einheiten",
    .profiles               = "Profile",
    .about                  = "Über",
    .lang_label             = "Sprache",
    .theme_label            = "Thema",
    .theme_dark             = "Dunkel",
    .theme_light            = "Hell",
    .brightness             = "Helligkeit",
    .bl_timeout             = "Hintergrundlicht",
    .bl_1min                = "1 Min",
    .bl_5min                = "5 Min",
    .bl_never               = "Nie",
    .units_c                = "°C",
    .units_f                = "°F",
    .sleep_timer_label      = "Schlaf-Timer",
    .sleep_temp_label       = "Schlaftemperatur",
    .sl_2min                = "2 Min",
    .sl_10min               = "10 Min",
    .save_current           = "Aktuell speichern",
    .factory_reset          = "Werksreset",
    .confirm_factory_reset  = "Auf Werkseinstellungen zurücksetzen?",
    .confirm_yes            = "Ja",
    .confirm_no             = "Nein",
    .firmware               = "Firmware",
    .uptime                 = "Laufzeit",
    .tool_type              = "Werkzeugtyp",
    .tool_iron              = "Lötkolben",
    .tool_gun               = "Heißluft",
    .airflow                = "Luftstrom",
    .pwr_label              = "PWR",
    .temp_step              = "Temp-Schritt",
    .beep_touch             = "Berührungs-Beep",
    .alert_overheat         = "Überhitzungsalarm",
    .alert_ready            = "Bereit-Signal",
    .ch_color               = "Kanalfarbe",
    .add_profile            = "Hinzufügen",
    .edit_profile           = "Bearbeiten",
    .delete_profile         = "Löschen",
    .profile_name           = "Name",
    .pid_kp                 = "Kp",
    .pid_ki                 = "Ki",
    .pid_kd                 = "Kd",
    .temp_offset            = "Offset",
    .apply_ch1              = "Anwenden CH1",
    .apply_ch2              = "Anwenden CH2",
};

static const ui_strings_t LANG_UK = {
    .channel_1              = "КАНАЛ 1",
    .channel_2              = "КАНАЛ 2",
    .current_temp           = "ПОТОЧНА",
    .setpoint               = "УСТАВКА",
    .settings               = "Налаштування",
    .back                   = "< Назад",
    .sound                  = "Звук",
    .sleep                  = "Сон",
    .display                = "Дисплей",
    .units                  = "Одиниці",
    .profiles               = "Профілі",
    .about                  = "Про систему",
    .lang_label             = "Мова / Language",
    .theme_label            = "Тема",
    .theme_dark             = "Темна",
    .theme_light            = "Світла",
    .brightness             = "Яскравість",
    .bl_timeout             = "Таймаут підсвітки",
    .bl_1min                = "1 хв",
    .bl_5min                = "5 хв",
    .bl_never               = "Ніколи",
    .units_c                = "°C",
    .units_f                = "°F",
    .sleep_timer_label      = "Таймер сну",
    .sleep_temp_label       = "Температура сну",
    .sl_2min                = "2 хв",
    .sl_10min               = "10 хв",
    .save_current           = "Зберегти поточні",
    .factory_reset          = "Скидання до заводських",
    .confirm_factory_reset  = "Скинути до заводських налаштувань?",
    .confirm_yes            = "Так",
    .confirm_no             = "Ні",
    .firmware               = "Прошивка",
    .uptime                 = "Час роботи",
    .tool_type              = "Тип інструменту",
    .tool_iron              = "Паяльник",
    .tool_gun               = "Фен",
    .airflow                = "Потік",
    .pwr_label              = "МОЩ",
    .temp_step              = "Крок температури",
    .beep_touch             = "Біп при торканні",
    .alert_overheat         = "Алерт перегріву",
    .alert_ready            = "Сигнал прогріву",
    .ch_color               = "Колір каналу",
    .add_profile            = "Додати",
    .edit_profile           = "Змінити",
    .delete_profile         = "Видалити",
    .profile_name           = "Ім'я",
    .pid_kp                 = "Kp",
    .pid_ki                 = "Ki",
    .pid_kd                 = "Kd",
    .temp_offset            = "Зміщення",
    .apply_ch1              = "Застосувати CH1",
    .apply_ch2              = "Застосувати CH2",
};

#define LANG_COUNT 4
static const ui_strings_t *LANGS[LANG_COUNT] = { &LANG_RU, &LANG_EN, &LANG_DE, &LANG_UK };

const ui_strings_t *ui_lang = &LANG_RU;

void ui_strings_init(void) { }

void ui_strings_set(uint8_t idx)
{
    if (idx >= LANG_COUNT) idx = 0;
    ui_lang = LANGS[idx];
}

void ui_strings_refresh(void)
{
    /* No-op stub — live label refresh will be wired in a follow-up task */
}
